In [53]:
# each category store in seperate file 
# inner join

import pandas as pd
import numpy as np
import glob,os
from functools import reduce

path=r'../Raw_data/stock/'
label_name = glob.glob(os.path.join(path, "*"))

for l_name in label_name:
    file = glob.glob(os.path.join(l_name, "*.csv"))
    label = l_name[18:]
    dl= []
    col_name = ['Date']
    for f in file:
        dfi = pd.read_csv(f)
        to_drop = ['Open','High','Low','Adj Close','Volume']
        dfi.drop(to_drop,inplace=True,axis = 1)        
        dl.append(dfi)
        s = f.split('/')[-1].split('.')[0]
        col_name.append(s)
    df_final = reduce(lambda left,right: pd.merge(left,right,on='Date', how='inner'), dl)
    df_final.columns = col_name
    df_final.set_index('Date',inplace=True)
    df_final.sort_index(inplace=True)
    df_final.to_csv("../Output/Stock_Price_Result/price/"+label+"_innerjoin_clean.csv")
    # normoalization
    result = 100.0 * df_final/df_final.iloc[0]
    result.to_csv("../Output/Stock_Price_Result/rate/"+label+"_rate_innerjoin_clean.csv")

In [54]:
# all in one file
# inner join

import pandas as pd
import numpy as np
import glob,os
from functools import reduce

path=r'../Raw_data/stock/'
label_name = glob.glob(os.path.join(path, "*"))

dl= []
col_name = ['Date']
    
for l_name in label_name:
    file = glob.glob(os.path.join(l_name, "*.csv"))
    label = l_name[18:]

    for f in file:
        dfi = pd.read_csv(f)
        to_drop = ['Open','High','Low','Adj Close','Volume']
        dfi.drop(to_drop,inplace=True,axis = 1)
        dl.append(dfi)
        s = f.split('/')[-1].split('.')[0]
        c_s = label + '_' + s
        col_name.append(c_s)
df_final = reduce(lambda left,right: pd.merge(left,right,on='Date', how='inner'), dl)
df_final.columns = col_name
df_final.set_index('Date',inplace=True)
df_final.sort_index(inplace=True)
df_final.to_csv("../Output/Stock_Price_Result/price/all_innerjoin_clean.csv")

# normalization
result = 100.0 * df_final/df_final.iloc[0]
result.to_csv("../Output/Stock_Price_Result/rate/all_rate_innerjoin.csv")
result

,restaurant_Starbucks,restaurant_Kura Sushi,restaurant_Carrols restaurant group,restaurant_Dine Brands,restaurant_Ark Restaurants,transport_UAL,transport_JBLU,transport_ALK,transport_AAL,transport_DAL,...,medicine & health_Medtronic plc,medicine & health_Johnson & Johnson,medicine & health_CVS,medicine & health_3M,medicine & health_General Electric Company,travel_Hilton,travel_Disney,travel_Expedia,travel_Universal,travel_Booking
Date,,,,,,,,,,,,,,,,,,,,,
2019-11-26,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
2019-11-27,101.430935,101.496768,97.885572,102.254896,100.400395,100.312636,99.689441,99.611169,99.655773,99.321269,...,101.023982,100.422834,100.133439,100.815461,103.125000,100.996964,99.894485,102.225578,100.620866,101.006114
2019-11-29,101.028858,104.935283,98.507463,103.251526,101.251251,100.043123,99.741201,99.380760,98.932878,99.738952,...,100.053891,100.233292,100.440346,100.319097,102.083333,99.696164,99.960435,102.376637,98.839695,100.877903
2019-12-02,100.011828,100.606804,97.512438,103.126949,100.350345,98.781797,99.378887,98.084676,96.660933,98.764360,...,99.622745,100.138516,100.813986,99.432729,98.958333,99.458792,99.327352,101.460218,98.386769,99.839996
2019-12-03,100.307476,102.022654,94.154229,102.354562,100.350345,95.806383,97.308483,95.924538,93.941487,96.797772,...,99.694598,99.992714,99.693084,97.600899,100.000000,98.699200,97.982065,100.090630,97.475823,99.603701
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-20,89.072850,41.626215,36.442786,38.046595,61.611612,29.959034,44.668737,42.093893,38.072290,41.141663,...,91.206323,110.570825,83.186547,84.896296,56.250000,68.628939,67.436034,60.372607,71.277353,74.789931
2020-04-21,85.998111,39.765374,35.820896,39.628753,57.607608,30.056057,43.115942,40.740208,37.865750,40.201880,...,87.676277,109.120066,80.397649,83.690840,53.125000,67.745915,66.301768,57.653573,66.941472,71.112500
2020-04-22,91.591768,42.516183,37.686567,39.740876,58.408408,27.899955,40.683230,39.645738,35.352841,39.105464,...,86.301985,111.533139,80.531087,84.860843,55.208333,67.214205,66.598522,61.852967,70.183208,71.789602
2020-04-23,88.871811,44.983821,37.437811,38.432791,55.055055,27.727467,41.459627,40.610599,35.283994,39.122869,...,86.077428,113.370268,81.772081,85.286300,54.166667,68.306117,66.605118,63.816714,70.050888,72.054509
2020-04-24,89.380326,42.961167,36.815920,38.358044,53.303303,27.554979,41.149068,40.336980,35.490535,39.001045,...,89.194288,112.896408,83.146516,86.864033,57.291667,67.764910,66.730416,67.039273,70.493641,72.201268

In [17]:
# each category store in seperate file 
# outerjoin

import pandas as pd
import numpy as np
import glob,os
from functools import reduce

path=r'../Raw_data/stock/'
label_name = glob.glob(os.path.join(path, "*"))

for l_name in label_name:
    file = glob.glob(os.path.join(l_name, "*.csv"))
    label = l_name[18:]
    dl= []
    col_name = ['Date']
    for f in file:
        dfi = pd.read_csv(f)
        to_drop = ['Open','High','Low','Adj Close','Volume']
        dfi.drop(to_drop,inplace=True,axis = 1)
        dl.append(dfi)
        s = f.split('/')[-1].split('.')[0]
        col_name.append(s)
    df_final = reduce(lambda left,right: pd.merge(left,right,on='Date', how='outer'), dl)
    df_final.columns = col_name
    df_final.set_index('Date',inplace=True)
    df_final.sort_index(inplace=True)
    df_final.to_csv("../Output/Stock_Price_Result/"+label+"_outerjoin_clean.csv")